server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: a2144
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Other options: create, create-drop, update, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    username: postgres
    password: a2144
